# Generated by Django 5.0.6 on 2024-06-20 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_notes", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
