# Generated by Django 5.0.6 on 2024-06-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_notes", "0002_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postitnote",
            name="author",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="postitnote",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
